### ISSUE TITLE
Sometime socket is already opened or closed and python throws an error

### ISSUE THREAD

**Issue by zmedia786** [harwee/IQOption-Api#11]
Hello sometimes the socket is open and sometimes it is closed. Can you kindly place a check when socket is not opened it opens the socket and when it is already opened then executes the remaining code.

**Comment by harwee** [comment]
yeah, that is a known problem, I think the problem is with heartbeat, It's not implemented on client side. I will look into it.

**Comment by jackynguyen93** [comment]
do we have a fix version for it

**Comment by tayyabghumman** [comment]
have you fixed this issue ?

**Comment by mjdileep** [comment]
start_socket_connection() is already called in login function. That's why. Please check.
![image](https://user-images.githubusercontent.com/6938724/47257612-c4bdbd80-d4ad-11e8-9f65-751a1ae7d4bd.png)
