### ISSUE TITLE
no print balance...

### ISSUE THREAD

**Issue by remarco** [harwee/IQOption-Api#13]
<code>### Initialisation
from iqoption_api import IQOption
import time
api = IQOption("user pass")
api.login() # Returns True if successful else False
for i in range(20):
         print(api.real_balance) # prints real account balance
         time.sleep(1)
        print(api.practice_balance) # prints practice account balance</code>
Output is :
On connect
No handlers could be found for logger "websocket"
0
0
0
no practice no real account printed.

**Comment by harwee** [comment]
is websocket-client installed?
