### ISSUE TITLE
Helping you out

### ISSUE THREAD

**Issue by SeanStayn** [harwee/IQOption-Api#17]
Hey, I want to help you with extending this repository. Can you give me a hint, how I can analyze the websocket stream? Which programs do you use, to know the API commands? 

Sorry, I know this is not an issue, but I don't know, how I should contact you..

**Comment by SeanStayn** [comment]
Sorry, stupid question... closed...

**Comment by hamez0r** [comment]
@SeanStayn  I have the exact same question, why did you conclude it's stupid? I would also want to know how to find out the API commands, in case there's another problem showing up.

**Comment by SeanStayn** [comment]
Because I have figured out, how it works. :)

I'm using Chrome:

1. Go to IqOptions trade room
2. Open DevTools by pressing Command+Option+I (Mac) or Control+Shift+I (Windows, Linux). This shortcut opens the Console panel.
3. Select the "Network" tab
4. Select the "WS" tab in the "Network" tab
5. Refresh the page (F5)
6. After loading you can see the open web sockets. Double-click on the web socket and you can see what you want! :)

Have fun!

**Comment by hamez0r** [comment]
Thanks a lot, that's great!
