### ISSUE TITLE
API Documentation - IQOption

### ISSUE THREAD

**Issue by nvrossett** [harwee/IQOption-Api#21]
Hello guys

I want to develop an api in NodeJS to make a tool I'm needing.
Could you tell me where you found the documentation to develop your api?

I'm looking for but I'm not finding anything.

**Comment by harwee** [comment]
There is no official support for the API, all the endpoints are extracted by monitoring the network activity of the website in bowser developer tools.

**Comment by nvrossett** [comment]
Awesome job... congratulations
