### ISSUE TITLE
market_data

### ISSUE THREAD

**Issue by cobolainen** [harwee/IQOption-Api#24]
how can i get market real time data? I've subscribed to EURUSD and i get KeyError 'EURUSD';

**Comment by tayyabghumman** [comment]
hello,

same issue here when i tried subscribe 

api.open_position(direction="put",
                    expiration_time=api.binary_expiration_list["AUDCAD-OTC"][-1]["time"],
                    market_name="AUDCAD-OTC",
                    price=5,
                    type="turbo"
                    )
KeyError: 'AUDCAD-OTC'
and 

api.open_position(direction="put",
                    expiration_time=api.binary_expiration_list["AUDCAD"][-1]["time"],
                    market_name="AUDCAD",
                    price=5,
                    type="turbo"
                    )
KeyError: 'AUDCAD'

hope to hear from you soon.

thanks

**Comment by harwee** [comment]
You can try the code written here https://github.com/harwee/IQOption-Api/tree/async If you face any difficulty please reopen the issue
