### ISSUE TITLE
how to sell an option?

### ISSUE THREAD

**Issue by LubeckHuaman** [harwee/IQOption-Api#25]
pls help me

**Comment by harwee** [comment]
You can check this

    api.open_position(direction="put",
                    expiration_time=api.binary_expiration_list["EURUSD"][-1]["time"],
                    market_name="EURUSD",
                    price=5,
                    type="turbo"
                    )

If this doesn't work for you, then the feature is not implemented yet in the current code. This library has only binary options implemented.
