### ISSUE TITLE
How to open binary position as quick as possible

### ISSUE THREAD

**Issue by aldhosutra** [harwee/IQOption-Api#33]
After i tried this API several times, i found that i must start the websocket connection first with `api.start()`, then after that i can execute buy_v2 command. 

Delay from `api.start()` is about 10 seconds in my case. I want to open binary position as soon as my signal is firing.

so, i want to know how i can quickly execute buy_v2 command, maybe without always calling `api.start()` everytime, or maybe by keeping my session alive?
How i can do that?

thanks

**Comment by harwee** [comment]
`api.start` is  just to initialize the whole session, it sets the session key and everything else to talk to server, the 10 sec delay is to ensure that asynchronous request is completed. if you cant wait for 10 seconds and want to start buying immediately try this branch https://github.com/harwee/IQOption-Api/tree/async it's written using asyncio so no manual delay is added to it other than the network latency and session stability is much higher for the code in that branch, so you can start the session beforehand and buy when ever you want immediately.

**Comment by aldhosutra** [comment]
cool, thanks for your response.
you're doing an amazing job!

**Comment by Big-Tigga** [comment]
Hi. I have failed to remove the 10 second delay when buying, I changed the 10 sec timeout in the buy methods to 1 sec but there is still a 10 second delay to buy each option, so if i am buying 6 at the same time the last one will be bought 60 seconds later which messes up the strike price significantly and causes losses, Can you tell me how you removed it? Thanks
