### ISSUE TITLE
Can't open a binary option

### ISSUE THREAD

**Issue by JoseCruz9807** [harwee/IQOption-Api#34]
I've been trying to place a binary option position but it pops an error in the expiration field. I'm trying the following:
from iqoption_api import IQOption
iqoption = IQOption("mail@email.com","pass")
iqoption.start()
EURUSD = iqoption.options["binary"]["EURUSD-OTC"]
EURUSD.subscribe_sync()
print(EURUSD.buy_v2_sync(EURUSD.sell,"put",1,1,"1M")) 
Does someone know where is the error?
Thanks in advance.

**Comment by harwee** [comment]
what is the error? and have you tried the code from this [branch](https://github.com/harwee/IQOption-Api/tree/async) Please try the code from async branch and check if it's working or not.

**Comment by JoseCruz9807** [comment]
I'm trying the code in that branch, it looks like it is sending the request correctly, but it returns the following:
{'name': 'buyComplete', 'request_id': 'r_15', 'msg': {'isSuccessful': False, 'message': ['Time for purchasing options is over, please try again later.'], 'result': {'request_id': None}}}

I've tried different numbers in the "expiration" parameter but it keeps sending the same response.

**Comment by harwee** [comment]
You are trying to open a position after the expiry time, try using `EURUSD.get_expiration_list_sync()` to get all the expiration times, you have to use one of these values for expiration.
