### ISSUE TITLE
Question: does this work for trading test mode?

### ISSUE THREAD

**Issue by cnexans** [harwee/IQOption-Api#38]
Hello

First of all, thanks for your great work. I am surfing through the code and I have a question that may be simple.

I know that IQ Option offers a test trading, that mode supports fake money to place orders, therefore losing/winning fake balance.

The question is: this API supports this IQ Option mode?

Best regards

**Comment by harwee** [comment]
Yes this API support practice mode

you can get the current active account by `api.active_balance_id` and get all balances by `api.balances.keys()` and change account by doing `api.change_balance(balance_id)`
