### ISSUE TITLE
merge from fork bitte-ein-bit/IQOption-Api

### ISSUE THREAD

**Issue by bitte-ein-bit** [harwee/IQOption-Api#5]
Hi harwee,

sure. go ahead and take the code over. Buying is working on forex. I do still have some trouble finding the correct current percentage of win/loss for a position. It's also most likely not python 2 compatible any more.

Sorry I had to update the master. It's the same commits as before but squashed into one, because with your message I realised I used the wrong git user/email.

**Comment by harwee** [comment]
I will look at the code in detail and fork it, but I would also like to keep Python 2 compatibility, I may pull your code and make some modifications to it before merging it.

**Comment by luidelia** [comment]
Hi @bitte-ein-bit ,
i use your repo, but buy forex don't work for me... can you help me?
Ty
