### ISSUE TITLE
How to issue a refund command?

### ISSUE THREAD

**Issue by MightyMaxSaviorOfTheUniverse** [harwee/IQOption-Api#53]
I'm unsure if there is already a way to trigger this command. To stop the bid mid way and get back some of your money in the process

Please point me in the right direction, or if you have your own code for it I would greatly appreciate if you share it here. 

Thank you in advance

**Comment by harwee** [comment]
This method does this for you,

https://github.com/harwee/IQOption-Api/blob/d94e8e7d13e6c5e1a554aad67a7c7690b3dda7ee/iqoption_api/portfolio_item.py#L10

**Comment by MightyMaxSaviorOfTheUniverse** [comment]
and how do I execute this in code?

I think I figured it out

first import
**from iqoption_api import portfolio_item**

then execute 

**Stock = iqoption.options["binary"]["EURUSD"]
portfolio_item.PortfolioItem.sell(Stock)**

**Comment by MightyMaxSaviorOfTheUniverse** [comment]
Conformation

This code works
