### ISSUE TITLE
Subscribing to candles Drains my internet!

### ISSUE THREAD

**Issue by MightyMaxSaviorOfTheUniverse** [harwee/IQOption-Api#54]
Hello

I see subscribing to candle intervals drains data at a hell of a rate. I would like to know if there is a way to cancel the the subscription and what is the max and min number of intervals you can subscribe to?

Stock.subscribe_to_candle_interval_sync(60)

I subscribe to 60 because in my program anything above 60 results in a null return. I tried re subscribing with 0 to see if it stops the sync but I'm uncertain if it really did anything at all

Any help would be greatly appreciated :)

**Comment by harwee** [comment]
There is no unsubscribe method implemented, I forgot to implement because I don't use IQOption anymore, but you can easily add unsubscribe if you can find the exact unsubscribe messages and use `IQOption.send_unsubscribe_message_sync` to send it. 

To find the Unsubscribe message you can open the iqoption website and monitor their socket connection while removing the option from your dashboard.

**Comment by MightyMaxSaviorOfTheUniverse** [comment]
Thanks. I added the following code to your file 'option.py'

`async def unsubscribe(self):
        await self._parent.send_unsubscribe_message({"name":"quote-generated","params":{"routingFilters":{"active_id":self._id}}})
        await self._parent.send_unsubscribe_message({"name":"expiration-top-computed","version":"1.0","params":{"routingFilters":{"instrument_type":self._type,"asset_id":str(self._id)}}})
        return True

async def unsubscribe_to_candle_interval(self, interval):
        if await self.is_valid_interval(interval):
            await self._parent.send_unsubscribe_message({"name":"candle-generated","params":{"routingFilters":{"size":self._id,"size":interval}}})
def unsubscribe_sync(self):
        return asyncio.run_coroutine_threadsafe(self.unsubscribe(),self._parent._async_loop).result()
def unsubscribe_to_candle_interval_sync(self, interval):
        return asyncio.run_coroutine_threadsafe(self.unsubscribe_to_candle_interval(interval),self._parent._async_loop).result()`
