### ISSUE TITLE
How to get market price?

### ISSUE THREAD

**Issue by robertpro** [harwee/IQOption-Api#8]
Hi, I would like to know how to get a market price, like AUDUSD: 0.77938 at 14:15:04

I can not understand api.market_data :(

please help!

**Comment by harwee** [comment]
You need to subscribe to the market before accessing the market data.
This is what is needed to get market data.

    api.subscribe_market("EURUSD")
    time.sleep(1) ## Artificial delay due to socket 
    eur_usd_market_data = api.market_data["EURUSD"] ## a dictionary with timestamp as keys

or you can get candle data for a market using this

     # api.update_candle_data(market_name,interval,start_time,end_time)
     api.update_candle_data("EURUSD",1,0,int(time.time())) ## get latest 1000 candles with 1 second interval

     time.sleep(1) ## Artificial delay

     # api.candle_data[market_name][interval] # list of lists  [time,open,close,high,low]
     print(api.candle_data["EURUSD][1]) # prints candles
